# Generated by Django 5.2.8 on 2025-11-11 18:08

import django.db.models.deletion
import matriculas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to=matriculas.models.ruta_archivo_tarea)),
                ('puntos', models.PositiveIntegerField(default=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='matriculas.curso')),
            ],
            options={
                'ordering': ['-fecha_limite'],
            },
        ),
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to=matriculas.models.ruta_entrega_tarea)),
                ('comentario_estudiante', models.TextField(blank=True)),
                ('comentario_profesor', models.TextField(blank=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente de revisión'), ('C', 'Calificado'), ('A', 'Aprobado'), ('R', 'Rechazado')], default='P', max_length=1)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_tareas', to='matriculas.estudiante')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='matriculas.tarea')),
            ],
            options={
                'ordering': ['-fecha_entrega'],
                'unique_together': {('tarea', 'estudiante')},
            },
        ),
    ]
