# Generated by Django 5.2.8 on 2025-11-12 01:22

import django.core.validators
import django.db.models.deletion
import matriculas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_tarea_entregatarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('semana', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('archivo', models.FileField(blank=True, null=True, upload_to=matriculas.models.ruta_archivo_material)),
                ('enlace', models.URLField(blank=True, null=True)),
                ('es_anuncio', models.BooleanField(default=False, help_text='Indica si este material es un anuncio')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='matriculas.curso')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('curso', 'Curso'), ('tarea', 'Tarea'), ('sistema', 'Sistema'), ('mensaje', 'Mensaje')], default='sistema', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matriculas.curso')),
                ('tarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matriculas.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
