# Generated by Django 5.2.8 on 2025-11-12 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0003_material_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='matriculas.curso'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='matriculas.tarea'),
        ),
    ]
